name: quick_action
description: A new Flutter application which demonstrates use of quick actions.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  quick_actions: ^0.3.0+1

  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true